### ISSUE TITLE
Command to list a player's save states

### ISSUE THREAD

**Issue by galacticwarrior9** [APDevTeam/Movecraft-Repair#11]
Some of the more prolific shipbuilders on my server have amassed a large number of save states and have difficulty recalling them all. A command that lists a player's save states would be beneficial for such players.

**Comment by TomLewis** [comment]
This would be beneficial to staff too.

Would be even better if we could get worldedit to load it into the clipboard so staff could paste a ship back in quickly. 

maybe thats solved by allowing us to change the save location for schematics?

**Comment by TylerS1066** [comment]
This should have been closed by #28
