### ISSUE TITLE
Left clicking in creative should not break sign

### ISSUE THREAD

**Issue by goodroach** [APDevTeam/Movecraft-Repair#16]
Suggestion: If I was in creative mode and I try to left click the sign to repair a state, if the repair sign is not within the ship, the sign breaks. I would like it if the sign didn't break. This is a simple to fix issue, but not really that important.

**Comment by TylerS1066** [comment]
I don't think we want to do this to all signs since it would make repair signs indestructible in creative, but we should do so on the successful/unsuccessful repair.

**Comment by TylerS1066** [comment]
Fixed as of https://github.com/APDevTeam/Movecraft-Repair/commit/bc6305d7013075c2b837f9286c4ce16e54d8f2ea
