### ISSUE TITLE
A blacklist of blocks that could be replaced when repairing

### ISSUE THREAD

**Issue by goodroach** [APDevTeam/Movecraft-Repair#17]
Right now, you are able to break blocks like bedrock using the repair system by simply repairing over it. There should be a check done to see if there is any blacklisted blocks whenever a block is being placed using the repair system.

**Comment by TomLewis** [comment]
Or at the very minimum hardcode in bedrock and barrier blocks, a normal SMP these are not accessable outside of staff.

**Comment by TylerS1066** [comment]
Closed in #44
