### ISSUE TITLE
Left click wont save a ship state, right click says no save state!

### ISSUE THREAD

**Issue by TomLewis** [APDevTeam/Movecraft-Repair#19]
Ahoy!
First time using Repair as its own plugin with movecraft.
Using 8.0.0 Beta 1 Movecraft with the latest [Movecraft-Repair 1.0.0 Beta 2](https://github.com/APDevTeam/Movecraft-Repair/releases/tag/1.0.0_beta-2) on PurPur 1.18.2.

For some reason after piloting a ship and left clicking the repair sign to create a ship state, nothing happens, nothign in chat, nothing in console. But right clicking tells me in big bold all caps that there is no save state.

If I look in the MoveCraft-Repair plugins folder its created a RepairStates folder and inside that another folder with my UUID, thats empty.

So its started the process to try and create a repair state, just not done it.

I am using the latest FAWE if that makes any differance?

**Comment by TylerS1066** [comment]
Were you using the new `RepairTool` (default is a firework rocket)?  As of beta 1, you are now required to double left click with the repair tool to save a state, and double right click to repair one.

**Comment by TomLewis** [comment]
I did not! Shall we start a wiki page, I couldnt find any docs at all and was reliant on a 8 year old video haha

**Comment by TylerS1066** [comment]
> I did not! Shall we start a wiki page, I couldnt find any docs at all and was reliant on a 8 year old video haha
Yes please!  I've created an [empty home page](https://github.com/APDevTeam/Movecraft-Repair/wiki) for Movecraft-Repair's wiki, let me know if you need access or something but I believe it's editable by anyone.

> Possible to add a fallback command? You can control ships via commands too, be nice to also have a command for the repair functions.
Unfortunately it is not currently possible.  The repair sign acts as the "anchor" of the repair state, and without it the plugin wouldn't know where to place the repair state in the world.

> Also can you reload the plugin live to change the configs?
Movecraft and it's addons do not like being reloaded, and overall it is considered bad practice to reload instead of restarting.

**Comment by TylerS1066** [comment]
I've never tried editing a wiki locally, but does the web editor work for you?

**Comment by TylerS1066** [comment]
Found the issue: https://github.com/desktop/desktop/issues/10732

Cloning it via command line or VS code worked fine.

**Comment by TylerS1066** [comment]
> No access to it sadly

Try now, I found a setting that restricted access to users with push access.

**Comment by TomLewis** [comment]
> > No access to it sadly
> 
> Try now, I found a setting that restricted access to users with push access.

There we go I can see it now!
