### ISSUE TITLE
Repair: QOL. Allow repair ship interaction in config / Feedback

### ISSUE THREAD

**Issue by TomLewis** [APDevTeam/Movecraft-Repair#21]
Allow setting how you wish to interact with the repair sign in the config, if its right/left click, with or without an item, if its double click or not.

I like the idea of a repair item, but maybe allowing it to be single click would be easier for players.

There are quite a few steps (from what ive figured out) to get the repair sign to trigger, trying to think of ways to make it simplier for a first time user, being able to change the interaction to just a single left click of the rocket would be nice to test, I cant tell if it just takes a while or if it does require 2 clicks as theres no feedback instantly. 

1. Spectify in config the interaction with the sign hand/item, and rightclick/left click and if there is multiple clicks required this to be set to.
2. Instant feedback when using the sign, if it does require multiple clicks
3. When the sign is created for the first time `Repair:` could we get a configurable message sent to the user in chat for how to use the repair sign?
2. Could we also have an option to change how the Reapir: sign is formatted in chat, most signs in servers use `[repair]` brackets and change the color of the text on the sign after its activated for feedback for the user.

**Comment by TylerS1066** [comment]
It would be very difficult to allow full configuration of the interactions, but I think we could add a config option to switch between single and double clicks.

The reason we had moved to double clicks was due to many many players accidentally overwriting their saved states or repairing them at the wrong time (for example, into the side of a mountain by mistake).

**Comment by TomLewis** [comment]
That would be very handy, nothing else in Minecraft requires a double click, it's just not very In keeping with the game, there is shift+clicking but not any double clicking I can think of.

The feedback messages would be very handy for players too.

**Comment by TylerS1066** [comment]
Since the double click is integral to the design of the repair start process (the first step loads the state and checks the materials needed, then the second step executes), #32 is a compromise and the config option disables it for repair save.

**Comment by TomLewis** [comment]
Brilliant news!
