### ISSUE TITLE
Empty Repair signs line 2 generates filename

### ISSUE THREAD

**Issue by TomLewis** [APDevTeam/Movecraft-Repair#23]
Another QOL improvemnet to Repair: signs could be automatic filename generation, I suggest `Username_date_time` for a unique filename they cant overwrite. or `Username_no` an incremental number, or `Username_movecraft_type`.

Keep the filename option in line2, but if they leave it blank its auto generated for them and automatically put onto line 2 so they can see what was picked.

This is mostly a QOL for simplicity for them, so for learning how to make a repair sign all they need to know is `Repair:` or if #21 is implemented `[repair]`.

**Comment by TylerS1066** [comment]
We will not be implementing this, as it won't function as you mention it.  Let's say for example a player saves two empty sign states, `Username_0` and `Username_1`, how does Movecraft-Repair know which one to place back into the world?

**Comment by TomLewis** [comment]
> We will not be implementing this, as it won't function as you mention it. Let's say for example a player saves two empty sign states, `Username_0` and `Username_1`, how does Movecraft-Repair know which one to place back into the world?

Yeah that would require a database to keep track, ok sod the incremental one.

timestamp/date-time/shiptype-time would all work as its all time related.
