### ISSUE TITLE
Repair does not check permission if they are allowed to place blocks, GriefPrevention etc.

### ISSUE THREAD

**Issue by TomLewis** [APDevTeam/Movecraft-Repair#29]
1. Build a craft with a big nose
2. Save its state
3. Remove the nose and sail it next to someones claim
4. Repair your ship
5. It ignores trust permission on the GriefPrevention claim and replaces all the blocks in their base.

**What it should do:**
Straight up prevent you from doing the repair, "You do not have permission to build here".

**Comment by TylerS1066** [comment]
Movecraft and it's addons do not do anything with protection plugins, but support other addons which do.  This would need to be part of a "Movecraft-GriefPrevention" addon.  Movecraft-Repair already has a cancel-able [`ProtoRepairCreateEvent`](https://github.com/APDevTeam/Movecraft-Repair/blob/main/src/main/java/net/countercraft/movecraft/repair/events/ProtoRepairCreateEvent.java) which is fired on the first click of a repair sign.

**Comment by TomLewis** [comment]
What this? https://github.com/eirikh1996/Movecraft-GriefPrevention

It looks abandoned @TylerS1066, @eirikh1996 is this something that could easily be done? 

I definitely couldn't use "Prevent crafts from moving into claims" as my worlds seas are littered with claims and it would make sailing impossible, so I would actually need to disable the main feature of "Movecraft-GriefPrevention" if this would be the only way to simply have repair check if you are allowed to build in the location its pasting a schematic.
