### ISSUE TITLE
Sign interactions not working on 1.20.4

### ISSUE THREAD

**Issue by ADA331** [APDevTeam/Movecraft-Repair#30]
Sign interactions are buggy on the movecraft repair (dev build too) and the movecraft 1.20.4 dev build. They dont work and throw an error in console

**Comment by TylerS1066** [comment]
Can you try [this dev build](https://github.com/APDevTeam/Movecraft-Repair/actions/runs/8211497047)?  I believe this was already fixed in https://github.com/APDevTeam/Movecraft-Repair/commit/879554d0b007cbb7f6c535322b226bd7f8f67ca5.

**Comment by TylerS1066** [comment]
Able to replicate, it appears Mojang changed the way sign text is saved in 1.20 (again).
