### ISSUE TITLE
Lectern Repair inventory issues

### ISSUE THREAD

**Issue by drfiveminusmint** [APDevTeam/Movecraft-Repair#37]
Currently, repairing a ship that has a lectern with a book in it will put the lectern into a glitchy state, requiring the player to break and replace the lectern. It would probably be better to instead special-case filled lecterns to also fill in the original book's contents (potentially costing another written book or book and quill)

**Comment by TylerS1066** [comment]
This should probably be handled similar to [SignRepair](https://github.com/APDevTeam/Movecraft-Repair/blob/main/src/main/java/net/countercraft/movecraft/repair/tasks/SignRepair.java).  I worry however about decoding NMS json of books ourselves, we should probably figure out if WorldEdit has helper classes for that.

**Comment by TylerS1066** [comment]
Looking into it, WorldEdit does not handle decoding of NBT data, it merely passes it through without modifications.  We may need to reconsider our methodology for handling these operations.
