### ISSUE TITLE
Repair states overide issue

### ISSUE THREAD

**Issue by jamesol1** [APDevTeam/Movecraft-Repair#4]
**Is your feature request related to a problem?**
When using repair states through a factory/shipyard to duplicate, or in my case, completely rebuild crafts lost in a battle... it can be very easy to left click a saved state sign, instead of right click, for activating the building phase which then (if in this scenario) you have no vehicle there present and therefore overriding you previous save. For what i'm working on this would be disaterous as players won't likely be duplicating smaller sized crafts on AP, as so there is no previous duplicate to revert the save state back to. With the ability of much larger vehicles upwards of 50k blocks, this makes the issue that much worse in terms of build loss.

**Describe the solution you'd like**
Some kind of fail safe. Maybe even just a ''Are you sure you want to override this saved state'', message requiring you to left click again to confirm. Or **ideally** (this would fix the issue) an option/change that doesn't allow you to override saves, instead requiring you to create a new repair state sign name. Perhaps adding an ability to delete them through a command incase they build up would be good alongside. 

One thing i would add, which is something i mentioned in the discord, some kind of "/savedstates list" command. This would of course tie in great with the ability for players to delete their saved states too via command. Neither are crucial though.

**Comment by TylerS1066** [comment]
With https://github.com/APDevTeam/Movecraft/pull/362 merged, this is being transferred to Movecraft-Repair.

**Comment by TylerS1066** [comment]
Note: This, #10 and #5 are all tied closely together.
