### ISSUE TITLE
1.20.6 Factorys dont pase in sign text or items in containers

### ISSUE THREAD

**Issue by Lordchaz1313** [APDevTeam/Movecraft-Repair#45]
**Describe the bug**
1.20.6 Factorys don't place in sign text or items in containers. It seems to be directional for the sign portion of the problem. North-South states don't paste in signs but East-West ones do. However, both directions seem to not fill containers. 

**To Reproduce**
1. Pilot craft
2. Take factory state
3. Run factory state

**Expected behavior**
Signs should have text and containers should be filled with the words and items the original state saved with

**Screenshots**
![2024-09-11_09 47 10](https://github.com/user-attachments/assets/113b3fcb-a745-4ff0-b259-c3edfe283b1c)

![2024-09-11_09 47 14](https://github.com/user-attachments/assets/e8c59fb9-f3e2-4247-a5c8-3eeb019ee7be)

**Versions (please complete the following information):**
 - Movecraft: 8.0.0_beta-5
 - Addons: Movecraft-Repair v1.0.0
 - Minecraft [e.g. 1.20.6]

**Additional context**
I have run a few different states to ensure what I'm reporting is correct however my ability are limited.

**Comment by TylerS1066** [comment]
Please include actual version info.
