### ISSUE TITLE
Ability to cancel in-progress repairs

### ISSUE THREAD

**Issue by drfiveminusmint** [APDevTeam/Movecraft-Repair#5]
**Is your feature request related to a problem? Please describe.**
Players will sometimes start a repair mistakenly and have no way to cancel it.

**Describe the solution you'd like**
Some method (commands/signs/whatever) of cancelling a repair in progress.

**Comment by TylerS1066** [comment]
Note: This, #10 and #4 are all tied closely together.

**Comment by TylerS1066** [comment]
Closed in #32
