### ISSUE TITLE
Repair blocks

### ISSUE THREAD

**Issue by Pvprod34** [APDevTeam/Movecraft-Repair#7]
Config option to define certain blocks which would cover the repair cost for a defined list of blocks. Ideally if multiple ones could be setup. For example you might allow a oak log/plank to cover the cost of all oak plank related objects. Or a custom bought block repairs Xyz.

Would make it so decorating your craft isn't as punishing when it comes to repairing it. Players could of course fully customize what blocks repairs what, so balance wise its up to the admins. 

I believe there is already a similar feature in which stone slabs can be used to repair other stone slabs? Not sure how extensive this system is or if it updates to 1.16.5 blocks. A wiki page on what blocks repair what would be neat whether the above is added or not.

**Comment by TylerS1066** [comment]
For Movecraft 7, this was handled by any block with the same base ID number (such as colored wool or slabs), or in some special cases an explicit code (like redstone torches).  @cccm5 is planning to allow the [Spigot Tag system](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Tag.html) to be used in Movecraft 8's configuration files, so I was planning on allowing server owners to list what Tags they want as "replaceable" block groups.  For example, adding `SIGNS` to this list would allow somebody to supply an oak sign to repair a spruce sign.  

Tags apparently can be user configured via datapacks, but I've yet to figure that out.

**Comment by cccm5** [comment]
The idea with the support for tags is that you'd have something akin to `"#signs"` and that would be than recognized as the `#minecraft:signs` block tag. its possible that in the future an alternative specified other than `#` would be preferable as these are considered to be comments in yaml and thus require escaping via explicit string declarations (via quotations). 
For creating tags in data packs, [see here](https://minecraft.fandom.com/wiki/Tutorials/Creating_a_data_pack#Tags) on the wiki. I haven't messed around with them myself but in theory they should work fine (so long as you specify your namespace in the config declaration, as no declaration is implied to be `minecraft:`)
